// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU94knz0fgoVJmnM4gnq-iDehQXP2rsWU',
    appId: '1:235555889574:web:10aca528e7ed7a62d2af67',
    messagingSenderId: '235555889574',
    projectId: 'gestion-proyectos-invest',
    authDomain: 'gestion-proyectos-invest.firebaseapp.com',
    storageBucket: 'gestion-proyectos-invest.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByEg14QaXAyFz_ZB0eV6FGa5N3viYMs58',
    appId: '1:235555889574:android:f700480646ab8e9cd2af67',
    messagingSenderId: '235555889574',
    projectId: 'gestion-proyectos-invest',
    storageBucket: 'gestion-proyectos-invest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhkK-gBgrhQY5uEEneSzLO8ds1PGSP4rA',
    appId: '1:235555889574:ios:9bd08d16bfb0bf63d2af67',
    messagingSenderId: '235555889574',
    projectId: 'gestion-proyectos-invest',
    storageBucket: 'gestion-proyectos-invest.firebasestorage.app',
    iosBundleId: 'com.example.proyectoFinalMovil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhkK-gBgrhQY5uEEneSzLO8ds1PGSP4rA',
    appId: '1:235555889574:ios:9bd08d16bfb0bf63d2af67',
    messagingSenderId: '235555889574',
    projectId: 'gestion-proyectos-invest',
    storageBucket: 'gestion-proyectos-invest.firebasestorage.app',
    iosBundleId: 'com.example.proyectoFinalMovil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU94knz0fgoVJmnM4gnq-iDehQXP2rsWU',
    appId: '1:235555889574:web:6dfe0d7c63adc582d2af67',
    messagingSenderId: '235555889574',
    projectId: 'gestion-proyectos-invest',
    authDomain: 'gestion-proyectos-invest.firebaseapp.com',
    storageBucket: 'gestion-proyectos-invest.firebasestorage.app',
  );
}
